### ISSUE TITLE
Getting redirected to port 443 when connecting on localhost

### ISSUE THREAD

**Issue by ninoppp** [beabee-communityrm/beabee-deploy#7]
When connecting to localhost:8008, I get redirected to https://localhost/auth/login, which can't be reached. Manually adding a port to the url (http://localhost:8008/auth/login) gives a login window, but after successful login I get redirected to http://localhost/auth/login (which is once again unreachable).

**Comment by JumpLink** [comment]
As the ticket is now 2 years old, it is no longer up to date and can be closed. @ninoppp feel free to reopen it if the problem still exists
